//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{
    public partial class Blog
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl blogTitle;

        protected global::System.Web.UI.WebControls.TextBox txtBlogSearch;

        protected global::System.Web.UI.WebControls.Button btnBlogSearch;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkClearFilter;

        protected global::System.Web.UI.WebControls.ListView lvBlogPosts;

        protected global::System.Web.UI.WebControls.DataPager dpBlog;
    }
}
