//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{
    public partial class PostDetails
    {
        protected global::System.Web.UI.WebControls.Label lblTitle;

        protected global::System.Web.UI.WebControls.Label lblCreatedAt;

        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.Label lblAuthorName;

        protected global::System.Web.UI.WebControls.Literal litTags;

        protected global::System.Web.UI.WebControls.Label lblContent;

        protected global::System.Web.UI.WebControls.HyperLink lnkEdit;

        protected global::System.Web.UI.WebControls.Label lblCommentCount;

        protected global::System.Web.UI.WebControls.Repeater rptComments;

        protected global::System.Web.UI.WebControls.Panel pnlNoComments;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlAddComment;

        protected global::System.Web.UI.WebControls.TextBox txtComment;

        protected global::System.Web.UI.WebControls.Button btnSubmitComment;

        protected global::System.Web.UI.WebControls.Label lblCommentMessage;

        protected global::System.Web.UI.WebControls.Panel pnlLoginToComment;
    }
}
