//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{
    public partial class PostList
    {
        protected global::System.Web.UI.WebControls.Button btnNewPost;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.ListView lvBlogPosts;

        protected global::System.Web.UI.WebControls.DataPager dpPosts;
    }
}
