//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.Label lblInitial;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.Label lblPostCount;
        protected global::System.Web.UI.WebControls.Label lblRegisteredAt;
        protected global::System.Web.UI.WebControls.Label lblLastLogin;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
