//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{


    public partial class Signup
    {

        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.WebControls.Button btnSignup;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
