//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtBlogEngine
{
    public partial class Site_Mobile
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liPosts;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogin;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSignup;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liUser;

        protected global::System.Web.UI.WebControls.Label lblUserName;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogout;

        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder FeaturedContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
